"""m15 nucleo inicial

Revision ID: f2efc6e45b12
Revises:
Create Date: 2026-07-17 19:42:12.351959

"""
from alembic import op
import sqlalchemy as sa


revision = 'f2efc6e45b12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=True),
    sa.Column('entidade_id', sa.String(length=36), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entidade'), ['entidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entidade_id'), ['entidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts_utc'), ['ts_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('code_sequences',
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix', name=op.f('pk_code_sequences'))
    )
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_name', sa.String(length=300), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('modo', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('ambiguous_rows', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_sha256'), ['sha256'], unique=False)
        batch_op.create_index('uq_import_batch_executado', ['source_type', 'sha256'], unique=True, sqlite_where=sa.text("modo = 'executado'"), postgresql_where=sa.text("modo = 'executado'"))

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=400), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('import_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('legacy_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows'))
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_rows_legacy_id'), ['legacy_id'], unique=False)

    op.create_table('legacy_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('legacy_source', sa.String(length=120), nullable=False),
    sa.Column('legacy_id', sa.String(length=120), nullable=False),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_legacy_aliases_import_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_aliases')),
    sa.UniqueConstraint('entidade', 'legacy_source', 'legacy_id', name='uq_legacy_alias')
    )
    with op.batch_alter_table('legacy_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legacy_aliases_entity_id'), ['entity_id'], unique=False)

    op.create_table('partners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('legacy_source', sa.String(length=120), nullable=True),
    sa.Column('legacy_id', sa.String(length=120), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_partners_import_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners')),
    sa.UniqueConstraint('public_code', name=op.f('uq_partners_public_code'))
    )
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('nome_completo', sa.String(length=300), nullable=False),
    sa.Column('nome_normalizado', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nao_contatar', sa.Boolean(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('legacy_source', sa.String(length=120), nullable=True),
    sa.Column('legacy_id', sa.String(length=120), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_people_import_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('public_code', name=op.f('uq_people_public_code'))
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_nome_normalizado'), ['nome_normalizado'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=120), nullable=True),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registrado_por', sa.String(length=36), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_consents_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_person_id'), ['person_id'], unique=False)

    op.create_table('consultations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('data_consulta', sa.Date(), nullable=True),
    sa.Column('data_consulta_original', sa.String(length=40), nullable=True),
    sa.Column('data_consulta_precisao', sa.String(length=15), nullable=True),
    sa.Column('data_consulta_dia_assumido', sa.Boolean(), nullable=False),
    sa.Column('modalidade', sa.String(length=30), nullable=True),
    sa.Column('profissional', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=120), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('idempotency_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('legacy_source', sa.String(length=120), nullable=True),
    sa.Column('legacy_id', sa.String(length=120), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_consultations_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_consultations_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_consultations_idempotency_key')),
    sa.UniqueConstraint('public_code', name=op.f('uq_consultations_public_code'))
    )
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultations_data_consulta'), ['data_consulta'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultations_person_id'), ['person_id'], unique=False)

    op.create_table('followups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('origem_entidade', sa.String(length=40), nullable=True),
    sa.Column('origem_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_date_manual', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('controlado_por_parceiro', sa.Boolean(), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('concluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluido_por', sa.String(length=36), nullable=True),
    sa.Column('resultado', sa.String(length=120), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_followups_partner_id_partners')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_followups_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_followups')),
    sa.UniqueConstraint('public_code', name=op.f('uq_followups_public_code'))
    )
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followups_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_origem_id'), ['origem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_person_id'), ['person_id'], unique=False)
        batch_op.create_index('uq_followup_pendente_origem', ['person_id', 'tipo', 'origem_id'], unique=True, sqlite_where=sa.text("status = 'pendente' AND origem_id IS NOT NULL"), postgresql_where=sa.text("status = 'pendente' AND origem_id IS NOT NULL"))
        batch_op.create_index('uq_followup_pendente_sem_origem', ['person_id', 'tipo'], unique=True, sqlite_where=sa.text("status = 'pendente' AND origem_id IS NULL"), postgresql_where=sa.text("status = 'pendente' AND origem_id IS NULL"))

    op.create_table('identity_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('import_row_id', sa.String(length=36), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_person_id', sa.String(length=36), nullable=True),
    sa.Column('motivo', sa.String(length=60), nullable=False),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decidido_por', sa.String(length=36), nullable=True),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_identity_candidates_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['candidate_person_id'], ['people.id'], name=op.f('fk_identity_candidates_candidate_person_id_people')),
    sa.ForeignKeyConstraint(['import_row_id'], ['import_rows.id'], name=op.f('fk_identity_candidates_import_row_id_import_rows')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_identity_candidates_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_candidates'))
    )
    with op.batch_alter_table('identity_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_candidates_person_id'), ['person_id'], unique=False)
        batch_op.create_index('uq_identity_candidate_pendente', ['person_id', 'candidate_person_id', 'motivo'], unique=True, sqlite_where=sa.text("status = 'pendente'"), postgresql_where=sa.text("status = 'pendente'"))

    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('origem', sa.String(length=120), nullable=True),
    sa.Column('canal_entrada', sa.String(length=60), nullable=True),
    sa.Column('servico_interesse', sa.String(length=60), nullable=True),
    sa.Column('modalidade', sa.String(length=30), nullable=True),
    sa.Column('etapa', sa.String(length=30), nullable=False),
    sa.Column('data_primeiro_contato', sa.Date(), nullable=True),
    sa.Column('data_primeiro_contato_original', sa.String(length=40), nullable=True),
    sa.Column('data_primeiro_contato_precisao', sa.String(length=15), nullable=True),
    sa.Column('data_primeiro_contato_dia_assumido', sa.Boolean(), nullable=False),
    sa.Column('data_retomada_manual', sa.Date(), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('legacy_source', sa.String(length=120), nullable=True),
    sa.Column('legacy_id', sa.String(length=120), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_leads_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_leads_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('public_code', name=op.f('uq_leads_public_code'))
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_person_id'), ['person_id'], unique=False)

    op.create_table('partner_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_units_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_units')),
    sa.UniqueConstraint('public_code', name=op.f('uq_partner_units_public_code'))
    )
    with op.batch_alter_table('partner_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_units_partner_id'), ['partner_id'], unique=False)

    op.create_table('partnerships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_inicio_original', sa.String(length=40), nullable=True),
    sa.Column('data_inicio_precisao', sa.String(length=15), nullable=True),
    sa.Column('data_inicio_dia_assumido', sa.Boolean(), nullable=False),
    sa.Column('modelo_repasse', sa.String(length=20), nullable=False),
    sa.Column('percentual_repasse', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_repasse_fixo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('responsavel_soprolife', sa.String(length=120), nullable=True),
    sa.Column('responsavel_followup', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('percentual_repasse IS NULL OR (percentual_repasse >= 0 AND percentual_repasse <= 100)', name=op.f('ck_partnerships_percentual_faixa')),
    sa.CheckConstraint('valor_repasse_fixo IS NULL OR valor_repasse_fixo >= 0', name=op.f('ck_partnerships_valor_fixo_nao_negativo')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partnerships_partner_id_partners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partnerships')),
    sa.UniqueConstraint('public_code', name=op.f('uq_partnerships_public_code'))
    )
    with op.batch_alter_table('partnerships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partnerships_partner_id'), ['partner_id'], unique=False)

    op.create_table('person_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('valor_normalizado', sa.String(length=200), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('nao_discavel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_person_contacts_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_contacts'))
    )
    with op.batch_alter_table('person_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_contacts_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_contacts_valor_normalizado'), ['valor_normalizado'], unique=False)

    op.create_table('interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('direcao', sa.String(length=10), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('resultado', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('followup_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['followup_id'], ['followups.id'], name=op.f('fk_interactions_followup_id_followups')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_interactions_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions')),
    sa.UniqueConstraint('public_code', name=op.f('uq_interactions_public_code'))
    )
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interactions_person_id'), ['person_id'], unique=False)

    op.create_table('migration_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_candidate_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('decisao', sa.String(length=300), nullable=False),
    sa.Column('decidido_por', sa.String(length=36), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['identity_candidate_id'], ['identity_candidates.id'], name=op.f('fk_migration_decisions_identity_candidate_id_identity_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_decisions'))
    )
    op.create_table('partner_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('partner_unit_id', sa.String(length=36), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_contacts_partner_id_partners')),
    sa.ForeignKeyConstraint(['partner_unit_id'], ['partner_units.id'], name=op.f('fk_partner_contacts_partner_unit_id_partner_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_contacts')),
    sa.UniqueConstraint('public_code', name=op.f('uq_partner_contacts_public_code'))
    )
    with op.batch_alter_table('partner_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_contacts_partner_id'), ['partner_id'], unique=False)

    op.create_table('partner_settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('partnership_id', sa.String(length=36), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=True),
    sa.Column('periodo_fim', sa.Date(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valor_total IS NULL OR valor_total >= 0', name=op.f('ck_partner_settlements_valor_total_nao_negativo')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_settlements_partner_id_partners')),
    sa.ForeignKeyConstraint(['partnership_id'], ['partnerships.id'], name=op.f('fk_partner_settlements_partnership_id_partnerships')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_settlements'))
    )
    with op.batch_alter_table('partner_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_settlements_partner_id'), ['partner_id'], unique=False)

    op.create_table('spirometry_exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('data_exame', sa.Date(), nullable=True),
    sa.Column('data_exame_original', sa.String(length=40), nullable=True),
    sa.Column('data_exame_precisao', sa.String(length=15), nullable=True),
    sa.Column('data_exame_dia_assumido', sa.Boolean(), nullable=False),
    sa.Column('modalidade', sa.String(length=30), nullable=True),
    sa.Column('local_atendimento', sa.String(length=200), nullable=True),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.Column('partner_unit_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=120), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('idempotency_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('legacy_source', sa.String(length=120), nullable=True),
    sa.Column('legacy_id', sa.String(length=120), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_spirometry_exams_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_spirometry_exams_partner_id_partners')),
    sa.ForeignKeyConstraint(['partner_unit_id'], ['partner_units.id'], name=op.f('fk_spirometry_exams_partner_unit_id_partner_units')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_spirometry_exams_person_id_people')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spirometry_exams')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_spirometry_exams_idempotency_key')),
    sa.UniqueConstraint('public_code', name=op.f('uq_spirometry_exams_public_code'))
    )
    with op.batch_alter_table('spirometry_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spirometry_exams_data_exame'), ['data_exame'], unique=False)
        batch_op.create_index(batch_op.f('ix_spirometry_exams_person_id'), ['person_id'], unique=False)

    op.create_table('partner_referrals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('partner_unit_id', sa.String(length=36), nullable=True),
    sa.Column('partner_contact_id', sa.String(length=36), nullable=True),
    sa.Column('data_encaminhamento', sa.Date(), nullable=True),
    sa.Column('data_encaminhamento_original', sa.String(length=40), nullable=True),
    sa.Column('data_encaminhamento_precisao', sa.String(length=15), nullable=True),
    sa.Column('data_encaminhamento_dia_assumido', sa.Boolean(), nullable=False),
    sa.Column('servico_solicitado', sa.String(length=60), nullable=True),
    sa.Column('data_agendada', sa.Date(), nullable=True),
    sa.Column('data_realizacao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('spirometry_exam_id', sa.String(length=36), nullable=True),
    sa.Column('consultation_id', sa.String(length=36), nullable=True),
    sa.Column('financial_entry_id', sa.String(length=36), nullable=True),
    sa.Column('valor_cobrado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_recebido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tipo_repasse', sa.String(length=20), nullable=True),
    sa.Column('valor_repasse', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('percentual_repasse', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status_repasse', sa.String(length=30), nullable=True),
    sa.Column('laudo_enviado', sa.Boolean(), nullable=False),
    sa.Column('data_envio_laudo', sa.Date(), nullable=True),
    sa.Column('responsavel_soprolife', sa.String(length=120), nullable=True),
    sa.Column('observacao_operacional', sa.Text(), nullable=True),
    sa.Column('autorizacao_contato_soprolife', sa.Boolean(), nullable=True),
    sa.Column('responsavel_followup', sa.String(length=20), nullable=False),
    sa.Column('proximo_followup', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('legacy_source', sa.String(length=120), nullable=True),
    sa.Column('legacy_id', sa.String(length=120), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('percentual_repasse IS NULL OR (percentual_repasse >= 0 AND percentual_repasse <= 100)', name=op.f('ck_partner_referrals_percentual_faixa')),
    sa.CheckConstraint('valor_cobrado IS NULL OR valor_cobrado >= 0', name=op.f('ck_partner_referrals_valor_cobrado_nao_negativo')),
    sa.CheckConstraint('valor_recebido IS NULL OR valor_recebido >= 0', name=op.f('ck_partner_referrals_valor_recebido_nao_negativo')),
    sa.CheckConstraint('valor_repasse IS NULL OR valor_repasse >= 0', name=op.f('ck_partner_referrals_valor_repasse_nao_negativo')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_partner_referrals_consultation_id_consultations')),
    # FK cíclica p/ financial_entries criada DEPOIS, via create_foreign_key nomeada
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_partner_referrals_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['partner_contact_id'], ['partner_contacts.id'], name=op.f('fk_partner_referrals_partner_contact_id_partner_contacts')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_referrals_partner_id_partners')),
    sa.ForeignKeyConstraint(['partner_unit_id'], ['partner_units.id'], name=op.f('fk_partner_referrals_partner_unit_id_partner_units')),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_partner_referrals_person_id_people')),
    sa.ForeignKeyConstraint(['spirometry_exam_id'], ['spirometry_exams.id'], name=op.f('fk_partner_referrals_spirometry_exam_id_spirometry_exams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_referrals')),
    sa.UniqueConstraint('public_code', name=op.f('uq_partner_referrals_public_code'))
    )
    with op.batch_alter_table('partner_referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_referrals_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_referrals_person_id'), ['person_id'], unique=False)

    op.create_table('financial_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_code', sa.String(length=12), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=3), nullable=False),
    sa.Column('data_competencia', sa.Date(), nullable=True),
    sa.Column('data_competencia_original', sa.String(length=40), nullable=True),
    sa.Column('data_competencia_precisao', sa.String(length=15), nullable=True),
    sa.Column('data_competencia_dia_assumido', sa.Boolean(), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=True),
    sa.Column('origem_preco', sa.String(length=20), nullable=True),
    sa.Column('spirometry_exam_id', sa.String(length=36), nullable=True),
    sa.Column('consultation_id', sa.String(length=36), nullable=True),
    sa.Column('partner_referral_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('idempotency_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('legacy_source', sa.String(length=120), nullable=True),
    sa.Column('legacy_id', sa.String(length=120), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('valor > 0', name=op.f('ck_financial_entries_valor_positivo')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_financial_entries_consultation_id_consultations')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_financial_entries_import_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['partner_referral_id'], ['partner_referrals.id'], name=op.f('fk_financial_entries_partner_referral_id_partner_referrals')),
    sa.ForeignKeyConstraint(['spirometry_exam_id'], ['spirometry_exams.id'], name=op.f('fk_financial_entries_spirometry_exam_id_spirometry_exams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_entries')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_financial_entries_idempotency_key')),
    sa.UniqueConstraint('public_code', name=op.f('uq_financial_entries_public_code'))
    )
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_entries_data_competencia'), ['data_competencia'], unique=False)

    op.create_table('partner_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('partnership_id', sa.String(length=36), nullable=True),
    sa.Column('partner_referral_id', sa.String(length=36), nullable=True),
    sa.Column('settlement_id', sa.String(length=36), nullable=True),
    sa.Column('financial_entry_id', sa.String(length=36), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('idempotency_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valor > 0', name=op.f('ck_partner_transfers_valor_positivo')),
    sa.ForeignKeyConstraint(['financial_entry_id'], ['financial_entries.id'], name=op.f('fk_partner_transfers_financial_entry_id_financial_entries')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_transfers_partner_id_partners')),
    sa.ForeignKeyConstraint(['partner_referral_id'], ['partner_referrals.id'], name=op.f('fk_partner_transfers_partner_referral_id_partner_referrals')),
    sa.ForeignKeyConstraint(['partnership_id'], ['partnerships.id'], name=op.f('fk_partner_transfers_partnership_id_partnerships')),
    sa.ForeignKeyConstraint(['settlement_id'], ['partner_settlements.id'], name=op.f('fk_partner_transfers_settlement_id_partner_settlements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_transfers')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_partner_transfers_idempotency_key'))
    )
    with op.batch_alter_table('partner_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_transfers_partner_id'), ['partner_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('financial_entry_id', sa.String(length=36), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=30), nullable=False),
    sa.Column('alvo_id', sa.String(length=36), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valor > 0', name=op.f('ck_payment_allocations_valor_positivo')),
    sa.ForeignKeyConstraint(['financial_entry_id'], ['financial_entries.id'], name=op.f('fk_payment_allocations_financial_entry_id_financial_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_financial_entry_id'), ['financial_entry_id'], unique=False)

    # ### end Alembic commands ###

    # --- ajustes manuais (M15.1A) -----------------------------------------

    # 1) FK cíclica partner_referrals -> financial_entries, criada só agora
    #    que as duas tabelas existem (batch p/ compatibilidade SQLite).
    with op.batch_alter_table('partner_referrals', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_partner_referrals_financial_entry_id_financial_entries',
            'financial_entries', ['financial_entry_id'], ['id'],
        )

    # 2) Preseed das sequências de código público: o SELECT ... FOR UPDATE
    #    de alocação sempre encontra a linha (atomicidade sob concorrência).
    code_sequences = sa.table(
        'code_sequences',
        sa.column('prefix', sa.String),
        sa.column('next_value', sa.Integer),
    )
    op.bulk_insert(code_sequences, [
        {'prefix': p, 'next_value': 1}
        for p in ('PES', 'LEA', 'ESP', 'CON', 'CLI', 'UNI', 'CTT',
                  'PAR', 'ENC', 'INT', 'FUP', 'LAN')
    ])

    # 3) audit_logs append-only imposto pelo banco (PostgreSQL).
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("""
            CREATE FUNCTION m15_audit_append_only() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs e append-only (M15)';
            END;
            $$ LANGUAGE plpgsql
        """)
        op.execute("""
            CREATE TRIGGER trg_audit_append_only
            BEFORE UPDATE OR DELETE ON audit_logs
            FOR EACH ROW EXECUTE FUNCTION m15_audit_append_only()
        """)


def downgrade() -> None:
    # --- ajustes manuais (M15.1A): desfazer na ordem inversa --------------
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP TRIGGER IF EXISTS trg_audit_append_only ON audit_logs')
        op.execute('DROP FUNCTION IF EXISTS m15_audit_append_only()')

    # solta a FK cíclica ANTES de derrubar financial_entries
    with op.batch_alter_table('partner_referrals', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_partner_referrals_financial_entry_id_financial_entries',
            type_='foreignkey',
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_financial_entry_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('partner_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_transfers_partner_id'))

    op.drop_table('partner_transfers')
    with op.batch_alter_table('financial_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_entries_data_competencia'))

    op.drop_table('financial_entries')
    with op.batch_alter_table('partner_referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_referrals_person_id'))
        batch_op.drop_index(batch_op.f('ix_partner_referrals_partner_id'))

    op.drop_table('partner_referrals')
    with op.batch_alter_table('spirometry_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spirometry_exams_person_id'))
        batch_op.drop_index(batch_op.f('ix_spirometry_exams_data_exame'))

    op.drop_table('spirometry_exams')
    with op.batch_alter_table('partner_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_settlements_partner_id'))

    op.drop_table('partner_settlements')
    with op.batch_alter_table('partner_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_contacts_partner_id'))

    op.drop_table('partner_contacts')
    op.drop_table('migration_decisions')
    with op.batch_alter_table('interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interactions_person_id'))

    op.drop_table('interactions')
    with op.batch_alter_table('person_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_contacts_valor_normalizado'))
        batch_op.drop_index(batch_op.f('ix_person_contacts_person_id'))

    op.drop_table('person_contacts')
    with op.batch_alter_table('partnerships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partnerships_partner_id'))

    op.drop_table('partnerships')
    with op.batch_alter_table('partner_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_units_partner_id'))

    op.drop_table('partner_units')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_person_id'))

    op.drop_table('leads')
    with op.batch_alter_table('identity_candidates', schema=None) as batch_op:
        batch_op.drop_index('uq_identity_candidate_pendente', sqlite_where=sa.text("status = 'pendente'"), postgresql_where=sa.text("status = 'pendente'"))
        batch_op.drop_index(batch_op.f('ix_identity_candidates_person_id'))

    op.drop_table('identity_candidates')
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index('uq_followup_pendente_sem_origem', sqlite_where=sa.text("status = 'pendente' AND origem_id IS NULL"), postgresql_where=sa.text("status = 'pendente' AND origem_id IS NULL"))
        batch_op.drop_index('uq_followup_pendente_origem', sqlite_where=sa.text("status = 'pendente' AND origem_id IS NOT NULL"), postgresql_where=sa.text("status = 'pendente' AND origem_id IS NOT NULL"))
        batch_op.drop_index(batch_op.f('ix_followups_person_id'))
        batch_op.drop_index(batch_op.f('ix_followups_origem_id'))
        batch_op.drop_index(batch_op.f('ix_followups_due_date'))

    op.drop_table('followups')
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultations_person_id'))
        batch_op.drop_index(batch_op.f('ix_consultations_data_consulta'))

    op.drop_table('consultations')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_person_id'))

    op.drop_table('consents')
    op.drop_table('user_roles')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_nome_normalizado'))

    op.drop_table('people')
    op.drop_table('partners')
    with op.batch_alter_table('legacy_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legacy_aliases_entity_id'))

    op.drop_table('legacy_aliases')
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_legacy_id'))
        batch_op.drop_index(batch_op.f('ix_import_rows_batch_id'))

    op.drop_table('import_rows')
    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('uq_import_batch_executado', sqlite_where=sa.text("modo = 'executado'"), postgresql_where=sa.text("modo = 'executado'"))
        batch_op.drop_index(batch_op.f('ix_import_batches_sha256'))

    op.drop_table('import_batches')
    op.drop_table('code_sequences')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts_utc'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entidade_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entidade'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
