/**
 * manual-das-abas.gs — SoproLife Command Center (M14.3)
 *
 * ═══════════════════════════════════════════════════════════════════
 *  ARQUIVO GERADO — NÃO EDITAR À MÃO.
 *  Fonte de verdade: painel-soprolife/core/contracts/abas-manifest.json
 *  Para atualizar:  python3 painel-soprolife/scripts/generate-manual-abas-gs.py
 *  e cole este arquivo novamente no editor do Apps Script.
 * ═══════════════════════════════════════════════════════════════════
 *
 * Cria/atualiza a aba "Manual das Abas" com a documentação viva da
 * planilha: matriz-resumo de todas as abas + detalhe completo por aba
 * (tipo, status, relação com o Centro de Comando, quem grava, quem lê,
 * dados sensíveis, permissões e recomendação).
 *
 * SEGURANÇA — o que NÃO está neste arquivo:
 *   - ID ou URL da planilha real;
 *   - tokens, senhas ou chaves;
 *   - qualquer dado real de paciente (só metadados estruturais).
 *
 * Este script só escreve na aba "Manual das Abas". Nunca oculta,
 * renomeia ou exclui nenhuma outra aba.
 *
 * COMO EXECUTAR:
 *   1. Abra a planilha "SoproLife - Painel Interno - Dados Privados".
 *   2. Extensões → Apps Script → cole (ou atualize) este arquivo.
 *   3. Selecione atualizarManualDasAbasSoproLife e clique em "Executar".
 */

var _MA_ABA = "Manual das Abas";

// Conteúdo gerado a partir do manifesto (1 array por linha da aba).
var _MA_LINHAS = [
  ["MANUAL DAS ABAS — SoproLife Command Center", "", "", "", "", "", "", "", "", ""],
  ["Como esta planilha se conecta ao painel:", "", "", "", "", "", "", "", "", ""],
  ["", "1. Google Sheets (abas privadas desta planilha) — onde o dado real mora.", "", "", "", "", "", "", "", ""],
  ["", "2. Apps Script (command-center-api.gs + contratos-canonicos.gs) — recebe as escritas do painel via Web App com token; valida contra contratos versionados FAIL-CLOSED, faz upsert com patch seletivo e audita. IDs novos são emitidos pelo servidor (UUID).", "", "", "", "", "", "", "", ""],
  ["", "3. Geradores locais (scripts/read-*-adc.py, generate-*.py) — leem as abas via ADC somente-leitura e produzem arquivos locais.", "", "", "", "", "", "", "", ""],
  ["", "4. Arquivos .local.json — data-private/*.local.json (completos, chmod 600, nunca no git) e data/*-summary.local.json (só agregados seguros, chmod 644).", "", "", "", "", "", "", "", ""],
  ["", "5. Centro de Comando / Painel SoproLife — o navegador só carrega os summaries seguros; escrita volta pelo proxy local → Apps Script.", "", "", "", "", "", "", "", ""],
  ["", "6. update-local-data.sh orquestra os passos 3–4 (local e na VPS via timer soprolife-update-data).", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ MATRIZ DAS ABAS (visão rápida)", "", "", "", "", "", "", "", "", ""],
  ["Aba", "Tipo", "Status", "Fonte", "Seção no painel", "Dados pessoais?", "Dados financeiros?", "Pode ocultar?", "Pode excluir?", "Recomendação"],
  ["CRM Pacientes", "Cadastro", "Operacional", "Oficial", "CRM", "Sim", "Não", "Não", "Não", "NUNCA excluir"],
  ["CRM Espirometria", "Fonte operacional", "Operacional", "Oficial", "Entrada de Dados", "Sim", "Não", "Não", "Não", "NUNCA excluir"],
  ["CRM Consultas", "Fonte operacional", "Operacional", "Oficial", "Entrada de Dados", "Sim", "Não", "Não", "Não", "NUNCA excluir"],
  ["Financeiro_Lancamentos", "Fonte financeira", "Operacional", "Oficial", "Financeiro", "Não", "Sim", "Não", "Não", "NUNCA excluir"],
  ["Leads", "Cadastro", "Operacional", "Oficial", "Leads e Agendamentos", "Sim", "Não", "Não", "Não", "Manter visível"],
  ["CRM Clinicas", "Cadastro", "Operacional", "Oficial", "CRM", "Não", "Não", "Não", "Não", "Manter visível"],
  ["CRM Contatos B2B", "Cadastro", "Operacional", "Oficial", "CRM", "Sim", "Não", "Não", "Não", "Manter visível"],
  ["Base Prospecção B2B PCMSO", "Staging", "Operacional", "Oficial", "CRM", "Não", "Não", "Não", "Não", "Manter como fonte"],
  ["Follow-up WhatsApp", "Fonte operacional", "Operacional", "Oficial", "CRM", "Sim", "Não", "Não", "Não", "Manter visível"],
  ["Tarefas", "Fonte operacional", "Operacional", "Oficial", "Tarefas", "Não", "Não", "Não", "Não", "Manter visível"],
  ["Marketing Conteúdo", "Fonte operacional", "Operacional", "Oficial", "Marketing & SEO", "Não", "Não", "Não", "Não", "Manter visível"],
  ["Agenda Operacional", "Fonte operacional", "Apoio", "Oficial", "Painel Geral", "Não", "Não", "Não", "Não", "Manter visível"],
  ["Parceria Pastore - Atendimentos", "Staging", "Transição", "Oficial", "Parcerias → Pastore", "Sim", "Sim", "Não", "Não", "Transformar em visão/staging"],
  ["Parceria Pastore - Custos", "Fonte financeira", "Operacional", "Oficial", "Parcerias → Pastore", "Não", "Sim", "Não", "Não", "Manter como fonte"],
  ["Parceria Pastore - Config", "Configuração", "Operacional", "Oficial", "Parcerias → Pastore", "Não", "Sim", "Sim", "Não", "Manter como configuração"],
  ["Resumo Dashboard", "Resumo", "Apoio", "Derivada", "Painel Geral", "Não", "Não", "Sim", "Não", "Ocultar para usuários comuns"],
  ["Log Centro Comando", "Log", "Apoio", "Derivada", "Automações", "Não", "Não", "Sim", "Não", "Manter como log"],
  ["Log Auditoria", "Log", "Apoio", "Derivada", "Automações", "Não", "Não", "Sim", "Não", "Manter como log"],
  ["Leads Convertidos", "Arquivo", "Apoio", "Derivada", "Leads e Agendamentos", "Sim", "Não", "Sim", "Não", "Ocultar para usuários comuns"],
  ["Log Conversões Leads", "Log", "Apoio", "Derivada", "Leads e Agendamentos", "Sim", "Não", "Sim", "Não", "Manter como log"],
  ["Manual das Abas", "Relatório", "Apoio", "Derivada", "Automações", "Não", "Não", "Não", "Sim", "Manter visível"],
  ["_Backup_Leads_Demo_*", "Backup", "Arquivo", "Derivada", "Leads e Agendamentos", "Sim", "Não", "Sim", "Sim", "Ocultar para usuários comuns"],
  ["_Backup_Leads_Operacional_*", "Backup", "Arquivo", "Derivada", "Leads e Agendamentos", "Sim", "Não", "Sim", "Sim", "Ocultar para usuários comuns"],
  ["Financeiro", "Legado", "REMOVIDA", "Oficial", "Financeiro", "Não", "Sim", "Não", "Não", "NUNCA recriar"],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ CRM Pacientes", "Uma linha por PESSOA. Carteira-mãe de quem já realizou pelo menos um atendimento.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Representar o relacionamento com o paciente (não um atendimento): identificação mínima, contato privado, último serviço, próximo contato, consentimento.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Cadastro", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "CRM", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "CRM → Pacientes / Follow-up de pacientes", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script createPaciente (Nova entrada do painel — só ADICIONA linha, fail-closed)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs; contratos-canonicos.gs; sync-crm-pacientes.gs (BLOQUEADO — lança erro; nunca executar); converter-lead-em-paciente.gs (BLOQUEADO — conversão automática desativada até a M14.3B)", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/generate-followup-pacientes.py; scripts/inspect-crm-pacientes.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel/conversão) + manual pontual — consolidação em massa BLOQUEADA", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por atendimento novo", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "CRÍTICO — perda da carteira de pacientes; não excluir nunca.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "CRM Espirometria e CRM Consultas vinculam via paciente_id (colunas v2 — M14.3B); Follow-up de pacientes no painel lê daqui", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Contém telefone (privado). Nunca CPF, laudo, diagnóstico ou pedido médico. Nome/telefone jamais saem para arquivos commitáveis.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "NUNCA excluir", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "paciente_id, data_cadastro, primeiro_nome, telefone, ultimo_servico, status_relacionamento, proximo_contato, motivo_proximo_contato, canal, responsavel, consentimento_whatsapp, observacao_privada_minima", "", "", "", "", "", "", "", ""],
  ["  Colunas propostas (futuras)", "data_cadastro_precisao, id_legado", "", "", "", "", "", "", "", ""],
  ["  Observações", "MESTRE PERSISTENTE (M14.3A): nenhuma reescrita integral, nenhuma linha eliminada, nenhum ID recalculado. O sincronizador antigo (clearContents + dedupe por telefone/primeiro nome) está BLOQUEADO — nome sozinho nunca vincula; telefone gera apenas candidato; telefone compartilhado = ambiguous; candidato não confirmado = pending; sem dados = unmatchable. Cobertura auditada em modo read-only por reconciliar-historico.py; migração incremental real é a M14.3B (backup + autorização).", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ CRM Espirometria", "Uma linha por EXAME de espirometria realmente realizado — o histórico central de exames, de todas as origens.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Registrar cada exame (SoproLife direta, domiciliar, coworking/clínica, empresa/PCMSO, parceria Pastore ou outros) num único histórico operacional.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Fonte operacional", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Entrada de Dados", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Entrada de Dados → Nova Espirometria (grava); CRM → follow-up de pacientes (lê)", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script createEspirometria (fail-closed; ID do servidor; idempotência por chave separada: replay ou conflito 409 — nunca patch de reenvio)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs; contratos-canonicos.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/generate-followup-pacientes.py; scripts/inspect-crm-pacientes.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel) + manual pontual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por exame", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "CRÍTICO — histórico real de exames da empresa; não excluir nunca.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "vínculo com CRM Pacientes via paciente_id (coluna v2 — M14.3B); compartilha id_atendimento com Financeiro_Lancamentos", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Fonte OPERACIONAL: nunca usar para calcular valores (fonte monetária é Financeiro_Lancamentos). Todos os registros existentes são exames REAIS — ID antigo (ESP-NNNN, ESM-*), data incompleta ou ausência de lançamento financeiro NÃO tornam um registro teste.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "NUNCA excluir", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "exame_id, data_entrada, primeiro_nome, telefone, servico, origem, status_exame, data_exame, proximo_contato, motivo_proximo_contato, canal, responsavel, consentimento_whatsapp", "", "", "", "", "", "", "", ""],
  ["  Colunas propostas (futuras)", "paciente_id, id_legado, data_exame_precisao, local_atendimento, parceiro, unidade, modalidade, idempotency_key (técnica, sob demanda), idempotency_fingerprint (técnica, sob demanda)", "", "", "", "", "", "", "", ""],
  ["  Observações", "exame_id é SEMPRE UUID do servidor (M14.3A 2ª rodada); a chave do navegador vai para a coluna técnica idempotency_key (criada sob demanda) e serve só para replay/409. Exames Pastore devem entrar AQUI (local=Parceiro) — a aba Pastore-Atendimentos é staging isolado. Datas com validação valor+precisão (impossível = erro; mês/ano preserva precisão; vazio nunca vira hoje).", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ CRM Consultas", "Uma linha por CONSULTA/teleconsulta realizada.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Histórico de consultas médicas. Hoje contém 1 consulta real — e isso está correto.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Fonte operacional", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Entrada de Dados", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Entrada de Dados → Nova Consulta; CRM → follow-up", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script createConsulta (fail-closed; mesma idempotência da espirometria)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs; contratos-canonicos.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/generate-followup-pacientes.py; scripts/inspect-crm-pacientes.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel) + manual pontual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por consulta", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "CRÍTICO — histórico real de consultas.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "vínculo com CRM Pacientes via paciente_id (coluna v2 — M14.3B)", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Nunca registrar diagnóstico/conteúdo clínico — apenas logística do atendimento.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "NUNCA excluir", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "consulta_id, data_entrada, primeiro_nome, telefone, origem, tipo_consulta, status, medica, data_consulta, proximo_contato, motivo_proximo_contato, canal, responsavel, consentimento_whatsapp", "", "", "", "", "", "", "", ""],
  ["  Colunas propostas (futuras)", "paciente_id, id_legado, data_consulta_precisao, modalidade, idempotency_key (técnica, sob demanda), idempotency_fingerprint (técnica, sob demanda)", "", "", "", "", "", "", "", ""],
  ["  Observações", "consulta_id sequencial (CON-NNNN); canônico futuro CON-AAAAMMDD-HHMMSS-XXXXXX.", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Financeiro_Lancamentos", "FONTE FINANCEIRA ÚNICA: uma linha financeira por atendimento, sem identificação de paciente.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Guardar valores (tabela/cobrado/recebido/desconto), status de pagamento, forma e origem do preço — vinculados ao exame por id_atendimento.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Fonte financeira", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Financeiro", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Financeiro; Painel Geral (card de receita); Cérebro Operacional; timeline", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script registrarEspirometriaFinanceiro (id_atendimento OBRIGATÓRIO — nenhum órfão novo pela API; patch por presença; sem defaults monetários inventados)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs; contratos-canonicos.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-financeiro-lancamentos-adc.py; scripts/generate-ultimos-lancamentos.py; scripts/generate-saude-operacional.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel)", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por atendimento", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script (a escrita REJEITA campos de pessoa — _EF_CAMPOS_PROIBIDOS)", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "CRÍTICO — única fonte monetária oficial do painel.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "compartilha id_atendimento com CRM Espirometria; summary financeiro do painel deriva 100% daqui", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Nunca nome/telefone/CPF/e-mail/endereço do paciente ou pagador. Observação financeira é texto livre sanitizado e fica só no arquivo privado local. Valores ausentes ficam ausentes — nunca inventar.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "NUNCA excluir", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "id_lancamento, id_atendimento, criado_em, data_exame, tipo_movimento, servico, local_atendimento, valor_tabela, valor_cobrado, valor_recebido, desconto, status_exame, status_pagamento, forma_pagamento, origem_preco, observacao_financeira, fonte", "", "", "", "", "", "", "", ""],
  ["  Colunas propostas (futuras)", "data_recebimento, data_exame_precisao, estado_reconciliacao, papel_movimento, movimento_referencia", "", "", "", "", "", "", "", ""],
  ["  Observações", "Cardinalidade (M14.3A, registros-schemas.json): um atendimento pode ter N movimentos; no máximo UMA receita principal ativa; ajustes/complementos/estornos são append-only e referenciam o movimento original — duplicata é CONFLITO visível, nunca 'última linha vence' silencioso (ledger completo na M14.3B). Hoje há exames históricos sem lançamento (backfill futuro com valores reais, nunca inventados) e 3 lançamentos de 09/07/2026 órfãos a reconciliar — nunca apagar automaticamente. Ver reconciliar-historico.py.", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Leads", "Contatos interessados ANTES do primeiro atendimento (funil de entrada).", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Registrar interesse, etapa do funil e próxima ação. Lead vira paciente ao realizar o primeiro atendimento; lead B2B vira clínica/parceiro.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Cadastro", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Leads e Agendamentos", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Leads e Agendamentos", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script createLead / updateLeadStage / vincularLeadAClinica; edição manual", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs; converter-lead-em-paciente.gs (BLOQUEADO); organizar-leads-operacionais.gs (BLOQUEADO — migração destrutiva → M14.3B); limpar-leads-e-manual-abas.gs (aditivo: dropdowns/notas/Manual, sem remoção de linhas)", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-leads-sheets.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel) + manual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por contato novo", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "ALTO — funil comercial ativo.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "conversão cria linhas em CRM Pacientes/Espirometria/Consultas e move para Leads Convertidos", "", "", "", "", "", "", "", ""],
  ["  Segurança", "telefone_whatsapp e observacao são privados; nunca em arquivos commitáveis.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter visível", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "lead_id, data_contato, nome, telefone_whatsapp, servico_interesse, origem, canal, bairro_regiao, tem_pedido_medico, etapa, responsavel, proxima_acao, data_proxima_acao, observacao", "", "", "", "", "", "", "", ""],
  ["  Colunas propostas (futuras)", "tipo_lead, entidade_destino, entidade_id, data_conversao, status_operacional", "", "", "", "", "", "", "", ""],
  ["  Observações", "As colunas propostas B2B já são criadas sob demanda por vincularLeadAClinica (_LEAD_COLUNAS_EXTRA_B2B). Conversão automática de leads BLOQUEADA (M14.3A 2ª rodada): registrar atendimento pela tela do painel e atualizar a etapa; conversão canônica na M14.3B.", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ CRM Clinicas", "Pipeline B2B: uma linha por clínica/consultório/empresa em relacionamento comercial.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Controlar etapa comercial, próxima ação e prioridade das parcerias institucionais.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Cadastro", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "CRM", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "CRM → Clínicas e Parceiros", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script createClinicaB2B / registrarInteracaoClinica / updateCrmClinicaEtapa", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-crm-clinicas-adc.py; scripts/generate-followup-clinicas.py; scripts/promote-pcmso-to-crm.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel) + manual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por interação", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "ALTO — relacionamento comercial B2B.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "Base Prospecção B2B PCMSO promove entradas para cá; CRM Contatos B2B referencia clinica_id", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Dados institucionais (não PII de paciente); mesmo assim não expor observações em arquivos públicos.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter visível", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "clinica_id, nome_clinica, bairro, regiao, tipo_clinica, etapa, ultima_interacao, proxima_acao, data_proxima_acao, responsavel, prioridade, observacao", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ CRM Contatos B2B", "Pessoas de contato dentro das clínicas/empresas parceiras.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Separar a PESSOA (contato) da ENTIDADE (clínica) no funil B2B.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Cadastro", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "CRM", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "CRM → Contatos B2B", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script vincularLeadAClinica (_upsertContatoB2B)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-crm-contatos-b2b-adc.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel)", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por vínculo de lead B2B", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "ALTO — contatos comerciais reais.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "clinica_id aponta para CRM Clinicas", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Telefone/e-mail de contato profissional: privado, nunca em arquivo commitável.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter visível", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "contato_id, clinica_id, nome_contato, cargo, telefone_whatsapp, email, papel, status_relacionamento, ultima_interacao, proxima_acao, data_proxima_acao, responsavel, observacao", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Base Prospecção B2B PCMSO", "Lista bruta de alvos B2B/PCMSO ainda em prospecção.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Funil de entrada B2B: empresas/clínicas mapeadas antes de responderem. Quando avançam, são promovidas ao CRM Clinicas.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Staging", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "CRM", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "CRM → prospecção B2B (ações)", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script createClinicaB2B (escrita dupla); espelhamento de etapa (updateCrmClinicaEtapa); manual", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs; soprolife-sheets-template.gs (coluna Etapa)", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/generate-followup-clinicas.py; scripts/promote-pcmso-to-crm.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "manual + automática parcial", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por campanha de prospecção", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "MÉDIO — lista de prospecção reconstituível, mas com histórico de status.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "promoção alimenta CRM Clinicas", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Dados institucionais públicos (nome, bairro, telefone comercial).", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter como fonte", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "Nome da clínica/empresa, Tipo, Bairro/Região, Telefone/WhatsApp, Pessoa de contato, Origem da lista, Status, Interesse, Próximo passo, Data do próximo passo, Observações, Etapa", "", "", "", "", "", "", "", ""],
  ["  Observações", "Cabeçalho humano (não snake_case) — legado aceito; a promoção ao CRM normaliza.", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Follow-up WhatsApp", "Fila de mensagens/contatos futuros — ações, não cadastro.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Agendar retornos, confirmações e reengajamento com consentimento registrado.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Fonte operacional", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "CRM", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "CRM → follow-up", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script registrarInteracaoPaciente; conversão de lead", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs; converter-lead-em-paciente.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/inspect-crm-pacientes.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel)", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por follow-up", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "MÉDIO — fila operacional ativa.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "referencia pacientes por nome/telefone (proposta futura: paciente_id)", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Nunca enviar mensagem sem consentimento registrado.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter visível", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "followup_id, data_criacao, primeiro_nome, telefone, tipo_mensagem, data_prevista, status, canal, responsavel, template_usado, consentimento", "", "", "", "", "", "", "", ""],
  ["  Colunas propostas (futuras)", "paciente_id", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Tarefas", "Pendências operacionais, comerciais, marketing e documentos.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Visão única de tarefas com prioridade, responsável e prazo.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Fonte operacional", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Tarefas", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Tarefas", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "manual", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "soprolife-sheets-template.gs (estrutura)", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-sheets-summary-adc.py (agregados via Resumo Dashboard)", "", "", "", "", "", "", "", ""],
  ["  Atualização", "manual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "diária", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "MÉDIO — organização do dia a dia.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Não citar paciente identificável em título/observação de tarefa.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter visível", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "tarefa_id, area, titulo, prioridade, status, responsavel, prazo, origem, observacao", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Marketing Conteúdo", "Calendário editorial: posts, campanhas, SEO.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Planejar e acompanhar conteúdo por canal, com datas e status.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Fonte operacional", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Marketing & SEO", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Marketing & SEO", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "manual", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "soprolife-sheets-template.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-marketing-seo-adc.py; scripts/read-sheets-summary-adc.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "manual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "semanal", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "BAIXO-MÉDIO — histórico editorial.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Sem dados pessoais.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter visível", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "conteudo_id, canal, tema, formato, etapa, data_planejada, data_publicacao, cta, status, metrica_agregada, observacao", "", "", "", "", "", "", "", ""],
  ["  Observações", "O nome da aba aparece como 'Marketing Conteúdo' (_ABAS_OPERACIONAIS) e 'Marketing Conteudo' (resumo do template) em pontos diferentes do código — padronizar para o nome REAL da aba na planilha ao revisar; divergência de acento quebra getSheetByName.", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Agenda Operacional", "Agenda de exames, consultas, reuniões e visitas — sem dado sensível.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Organizar a rotina da equipe; dados clínicos ficam nos CRMs.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Fonte operacional", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Apoio", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Painel Geral", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Painel Geral (indiretamente, via resumo)", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "manual", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "soprolife-sheets-template.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-sheets-summary-adc.py (via Resumo Dashboard)", "", "", "", "", "", "", "", ""],
  ["  Atualização", "manual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "diária", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "BAIXO — agenda também existe no Google Calendar.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Usar primeiro nome ou código de evento; nunca nome completo de paciente.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter visível", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "evento_id, data, hora, tipo_evento, local, responsavel, status, observacao_anonima", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Parceria Pastore - Atendimentos", "STAGING/fila operacional dos atendimentos captados via parceria Pastore.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Captura rápida no formato do acordo comercial (repasse, custos por exame). O registro CANÔNICO do exame deve existir em CRM Espirometria (local_atendimento=Parceiro, parceiro=Pastore) e o financeiro em Financeiro_Lancamentos.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Staging", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Transição", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Parcerias → Pastore", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Parcerias → Pastore", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script _registrarAtendimentoPastore (pastore-staging.gs — writer ISOLADO, marcado staging/não canônico)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "pastore-staging.gs; command-center-api.gs (roteia com guarda fail-closed)", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-parcerias-pastore-adc.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (painel) + manual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por turno de atendimento (terças/sábados)", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios + Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "CRÍTICO enquanto for a única fonte dos atendimentos Pastore — os exames reais registrados aqui ainda NÃO estão no histórico central.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "Parceria Pastore - Config (preços/repasse); summary do painel Parcerias", "", "", "", "", "", "", "", ""],
  ["  Segurança", "paciente_nome e paciente_whatsapp nunca saem da planilha/data-private. Valores por linha nunca viram summary.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Transformar em visão/staging", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "data_atendimento, unidade, dia_semana, horario_inicio, horario_fim, origem, paciente_nome, paciente_whatsapp, tipo_exame, broncodilatador, valor_cobrado, forma_pagamento, recebido_por, repasse_pastore, custo_insumo, custo_deslocamento, custo_profissional, outros_custos, receita_bruta, custo_total, resultado_liquido, status, followup_status, consentimento_contato_futuro, observacao_privada_minima", "", "", "", "", "", "", "", ""],
  ["  Colunas propostas (futuras)", "id_atendimento, estado_reconciliacao", "", "", "", "", "", "", "", ""],
  ["  Observações", "Decisão M14.3A: writer isolado em pastore-staging.gs para deixar a fronteira explícita — esta aba NÃO é base canônica de pessoas nem de valores (Config não é prova de preço real). O modal do painel sinaliza 'staging/não canônico'. Alvo M14.3B: cada atendimento gera id_atendimento + linha canônica em CRM Espirometria + lançamento em Financeiro_Lancamentos (outbox idempotente); migração dos registros existentes só com autorização, via reconciliar-historico.py.", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Parceria Pastore - Custos", "Custos da parceria não amarrados a um atendimento específico.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Custo fixo mensal, deslocamento de dia inteiro, insumo em lote.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Fonte financeira", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Parcerias → Pastore", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Parcerias → Pastore (financeiro)", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "manual", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "—", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-parcerias-pastore-adc.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "manual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por custo", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "ALTO — custos reais da parceria.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "summary Pastore", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Valores por linha só agregados no summary.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter como fonte", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "data, unidade, tipo_custo, descricao, valor, pago_por, recorrente, observacao_privada_minima", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Parceria Pastore - Config", "Parâmetros da parceria: agenda, capacidade, preços e repasse.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Fonte de verdade da agenda e dos parâmetros comerciais da parceria.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Configuração", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "Operacional", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Parcerias → Pastore", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Parcerias → Pastore (agenda/ocupação)", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "manual", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "—", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-parcerias-pastore-adc.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "manual", "", "", "", "", "", "", "", ""],
  ["  Frequência", "rara (mudança de acordo)", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "sócios", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "ALTO — acordo comercial; sem ela ocupação/margem não calculam.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "summary Pastore usa capacidade para ocupação", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Valores de acordo comercial são sensíveis — não expor fora do painel privado.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter como configuração", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "unidade, status, dia_semana, horario_inicio, horario_fim, capacidade_estimada_por_turno, valor_exame_sem_bd, valor_exame_com_bd, repasse_pastore_tipo, repasse_pastore_valor, custo_insumo_padrao, custo_deslocamento_padrao, custo_profissional_padrao, observacao", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Resumo Dashboard", "Agregados gerados automaticamente para leitura do painel.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Métricas consolidadas (contagens por aba) em formato chave/valor para o conector de resumo.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Resumo", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Derivada", "", "", "", "", "", "", "", ""],
  ["  Status", "Apoio", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Painel Geral", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Painel Geral", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script atualizarResumoDashboardSoproLife (gatilho/menu)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "soprolife-sheets-template.gs; core/apps-script/resumo-dashboard-auto.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-sheets-summary-adc.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (gatilho onEdit + menu)", "", "", "", "", "", "", "", ""],
  ["  Frequência", "a cada edição monitorada", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "somente Apps Script (não editar à mão)", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "BAIXO — é derivada; o Apps Script recria. Excluir só quebra até a próxima geração.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "deriva de Leads/CRM Clinicas/Tarefas/Financeiro_Lancamentos/Marketing/Agenda", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Só agregados.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Ocultar para usuários comuns", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "chave, valor, atualizado_em", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Log Centro Comando", "Histórico das ações do Command Center (o que rodou, quando, resultado).", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Rastreabilidade das automações e escritas do painel.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Log", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Derivada", "", "", "", "", "", "", "", ""],
  ["  Status", "Apoio", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Automações", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Automações (indiretamente)", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script _logEntry (todas as ações)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "—", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por ação", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "somente Apps Script (append-only)", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "MÉDIO — perde trilha de auditoria operacional.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Telefone e observações nunca entram no log (regra de _logEntry).", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter como log", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "timestamp, acao, status, aba, id, executor, resumo", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Log Auditoria", "Trilha append-only das escritas (M1), com request_id, campo alterado e duração.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Auditoria fina das mutações: quem/o quê/quando/resultado, sem valores privados.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Log", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Derivada", "", "", "", "", "", "", "", ""],
  ["  Status", "Apoio", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Automações", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "Automações → resumo de auditoria", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "Apps Script _logAudit/_auditAcao", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "command-center-api.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/read-auditoria-adc.py", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por escrita", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "somente Apps Script (append-only)", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "MÉDIO — perde trilha de auditoria técnica.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Campos privados viram '[campo privado]' (_AUDIT_VALOR_PRIVADO).", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter como log", "", "", "", "", "", "", "", ""],
  ["  Observações", "Cabeçalho definido em _LOG_AUDITORIA_CABECALHO (command-center-api.gs).", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Leads Convertidos", "Arquivo dos leads já convertidos em paciente/clínica (saem da aba Leads).", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Preservar o histórico do funil sem poluir a lista ativa.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Arquivo", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Derivada", "", "", "", "", "", "", "", ""],
  ["  Status", "Apoio", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Leads e Agendamentos", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "—", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "(histórico) converter-lead-em-paciente.gs — hoje BLOQUEADO; dedupLeadsConvertidos só emite relatório (exclusão bloqueada)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "converter-lead-em-paciente.gs; command-center-api.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "—", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por conversão", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "somente Apps Script", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "MÉDIO — histórico de conversões.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "origem: aba Leads", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Mesmas regras de Leads.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Ocultar para usuários comuns", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "lead_id, data_contato, nome, telefone_whatsapp, servico_interesse, origem, etapa, responsavel, proxima_acao, data_proxima_acao, observacao", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Log Conversões Leads", "Log específico das conversões de lead (o que foi criado onde).", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Rastrear cada conversão: destinos criados e resultado.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Log", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Derivada", "", "", "", "", "", "", "", ""],
  ["  Status", "Apoio", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Leads e Agendamentos", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "—", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "converter-lead-em-paciente.gs; command-center-api.gs (_logConversaoLeads)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "converter-lead-em-paciente.gs; command-center-api.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "—", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por conversão", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "somente Apps Script (append-only)", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "BAIXO-MÉDIO — trilha de conversões.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Contém nome do lead — manter oculta.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter como log", "", "", "", "", "", "", "", ""],
  ["  Colunas canônicas", "data_hora, lead_id, nome, etapa, destinos_criados, resultado, followup_status", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Manual das Abas", "Documentação viva da planilha — gerada a partir deste manifesto.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Explicar cada aba e sua relação com o Centro de Comando, em linguagem simples.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Relatório", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Derivada", "", "", "", "", "", "", "", ""],
  ["  Status", "Apoio", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Automações", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "—", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "apps-script/manual-das-abas.gs (atualizarManualDasAbasSoproLife)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "manual-das-abas.gs; limpar-leads-e-manual-abas.gs (delega; SEM fallback — falha se o gerado não estiver instalado)", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "scripts/generate-manual-abas-gs.py (gera o .gs a partir deste manifesto)", "", "", "", "", "", "", "", ""],
  ["  Atualização", "manual (executar a função no Apps Script)", "", "", "", "", "", "", "", ""],
  ["  Frequência", "a cada mudança de arquitetura", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "somente Apps Script (regenerada por completo)", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "NENHUM — é regenerada pela função do Apps Script.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "core/contracts/abas-manifest.json é a fonte", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Só metadados.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Manter visível", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ _Backup_Leads_Demo_*", "Backups automáticos da aba Leads criados antes da limpeza de dados demo (padrão _Backup_Leads_Demo_YYYYMMDD_HHMM).", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Rede de segurança da execução de organizarLeadsEManualPlanilhasSoproLife.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Backup", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Derivada", "", "", "", "", "", "", "", ""],
  ["  Status", "Arquivo", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Leads e Agendamentos", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "—", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "limpar-leads-e-manual-abas.gs (_criarBackupLeads)", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "limpar-leads-e-manual-abas.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "—", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (uma por execução)", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por execução da limpeza", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "ninguém (snapshot)", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "BAIXO após conferência humana de que a aba Leads atual está íntegra — manter as 2 mais recentes, excluir as demais SOMENTE por decisão humana.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Snapshot completo de Leads (contém telefones) — manter oculto.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Ocultar para usuários comuns", "", "", "", "", "", "", "", ""],
  ["  Observações", "Nenhuma exclusão automática — a matriz recomenda revisão humana com data marcada.", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ _Backup_Leads_Operacional_*", "Backups automáticos da aba Leads criados pela migração de cabeçalho (padrão _Backup_Leads_Operacional_YYYYMMDD_HHMM).", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Rede de segurança da execução de organizarLeadsOperacionaisSoproLife.", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Backup", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Derivada", "", "", "", "", "", "", "", ""],
  ["  Status", "Arquivo", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Leads e Agendamentos", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "—", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "organizar-leads-operacionais.gs", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "organizar-leads-operacionais.gs", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "—", "", "", "", "", "", "", "", ""],
  ["  Atualização", "automática (uma por execução)", "", "", "", "", "", "", "", ""],
  ["  Frequência", "por execução da migração", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "ninguém (snapshot)", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "BAIXO após conferência humana — mesma regra dos backups demo.", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "Snapshot completo de Leads — manter oculto.", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "Ocultar para usuários comuns", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["▶ Financeiro", "ABA REMOVIDA (M14.x) — antiga aba financeira manual.", "", "", "", "", "", "", "", ""],
  ["  Finalidade", "Substituída integralmente por Financeiro_Lancamentos (fonte financeira única).", "", "", "", "", "", "", "", ""],
  ["  Tipo", "Legado", "", "", "", "", "", "", "", ""],
  ["  Fonte oficial ou derivada", "Oficial", "", "", "", "", "", "", "", ""],
  ["  Status", "REMOVIDA", "", "", "", "", "", "", "", ""],
  ["  Seção no Centro de Comando", "Financeiro", "", "", "", "", "", "", "", ""],
  ["  Página do painel", "—", "", "", "", "", "", "", "", ""],
  ["  Quem grava (formulário/ação)", "—", "", "", "", "", "", "", "", ""],
  ["  Apps Script responsável", "—", "", "", "", "", "", "", "", ""],
  ["  Scripts locais que leem", "—", "", "", "", "", "", "", "", ""],
  ["  Atualização", "—", "", "", "", "", "", "", "", ""],
  ["  Frequência", "—", "", "", "", "", "", "", "", ""],
  ["  Contém dados pessoais?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados clínicos?", "Não", "", "", "", "", "", "", "", ""],
  ["  Contém dados financeiros?", "Sim", "", "", "", "", "", "", "", ""],
  ["  Contém apenas agregados?", "Não", "", "", "", "", "", "", "", ""],
  ["  Quem pode editar", "—", "", "", "", "", "", "", "", ""],
  ["  Pode ser ocultada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser arquivada?", "Não", "", "", "", "", "", "", "", ""],
  ["  Pode ser excluída?", "Não", "", "", "", "", "", "", "", ""],
  ["  Risco de exclusão", "—", "", "", "", "", "", "", "", ""],
  ["  Dependências", "—", "", "", "", "", "", "", "", ""],
  ["  Segurança", "NUNCA RECRIAR esta aba — nenhum template/setup/fluxo pode reintroduzi-la (ver soprolife-sheets-template.gs e docs/financeiro-fonte-unica.md).", "", "", "", "", "", "", "", ""],
  ["  Recomendação de uso", "NUNCA recriar", "", "", "", "", "", "", "", ""],
  ["", "", "", "", "", "", "", "", "", ""],
  ["Gerado por", "atualizarManualDasAbasSoproLife()  |  fonte: core/contracts/abas-manifest.json (versão 1.2.0, manifesto sha256 0f1c8122644a)", "", "", "", "", "", "", "", ""]
];

/**
 * Ponto de entrada: recria a aba "Manual das Abas" a partir do manifesto.
 */
function atualizarManualDasAbasSoproLife() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(_MA_ABA);
  if (!sheet) {
    sheet = ss.insertSheet(_MA_ABA);
  } else {
    sheet.clear();
  }

  var nCols = _MA_LINHAS[0].length;
  var linhas = _MA_LINHAS.concat([[
    "Atualizado em",
    Utilities.formatDate(new Date(), "America/Sao_Paulo", "dd/MM/yyyy HH:mm"),
    "", "", "", "", "", "", "", ""
  ]]);

  sheet.getRange(1, 1, linhas.length, nCols).setValues(linhas);

  // Título principal.
  sheet.getRange(1, 1, 1, nCols)
    .setFontWeight("bold").setFontSize(13)
    .setFontColor("#ffffff").setBackground("#08243d");

  // Seções (coluna A começa com "▶") e cabeçalho da matriz.
  for (var i = 0; i < linhas.length; i++) {
    var celA = String(linhas[i][0]);
    if (celA.indexOf("▶") === 0) {
      sheet.getRange(i + 1, 1, 1, nCols)
        .setFontWeight("bold").setFontColor("#ffffff").setBackground("#0b6e9e");
    }
    if (celA === "Aba") { // cabeçalho da matriz-resumo
      sheet.getRange(i + 1, 1, 1, nCols)
        .setFontWeight("bold").setBackground("#e8f1f5");
    }
  }

  sheet.setColumnWidth(1, 250);
  sheet.setColumnWidth(2, 560);
  for (var c = 3; c <= nCols; c++) sheet.setColumnWidth(c, 130);
  sheet.setFrozenRows(1);

  SpreadsheetApp.flush();
  Logger.log("Aba '" + _MA_ABA + "' atualizada com " + linhas.length + " linha(s).");
  _maAlertaSeguro("Manual das Abas atualizado (" + linhas.length + " linhas).");
}

/** Alerta via UI quando disponível; em execução pelo editor, só loga. */
function _maAlertaSeguro(mensagem) {
  try {
    SpreadsheetApp.getUi().alert(mensagem);
  } catch (e) {
    Logger.log("(alerta via UI indisponível neste contexto)");
  }
}

/** Item de menu opcional. */
function onOpen_manualAbas() {
  SpreadsheetApp.getUi()
    .createMenu("SoproLife")
    .addItem("Atualizar Manual das Abas", "atualizarManualDasAbasSoproLife")
    .addToUi();
}
